数据操作

In [1]:
import torch

In [ ]:
# 具有一个轴的张量对应数学上的向量（vector）
# 具有两个轴的张量对应数学上的矩阵（matrix）

In [7]:
x = torch.arange(12)
print(x)
print(x.shape)
X = x.reshape(3, -1)
print(X)
print(torch.randn(3, 4))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0.1390, -2.1918,  0.8226, -0.3847],
        [ 0.1018,  0.1034,  0.5202,  2.3747],
        [-2.1254,  1.4407, -1.7175,  1.1157]])


In [8]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [9]:
# 使用 X += Y 来减少操作的内存开销
before = id(X)
X += Y
id(X) == before

True